// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote360.Infrastructure.Persistence.Contexts;

#nullable disable

namespace eVote360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(eVote360AppContext))]
    [Migration("20260610191244_AddAssignPosition")]
    partial class AddAssignPosition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eVote360.Core.Domain.Entities.AssignPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ElectivePositionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlliance")
                        .HasColumnType("bit");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectivePositionId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("CandidateId", "ElectivePositionId", "PoliticalPartyId")
                        .IsUnique();

                    b.ToTable("AssignPositions", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ElectivePositionId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ElectivePositionId");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Citizens", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.ElectivePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ElectivePositions", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalAlliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReceivingPartyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestingPartyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceivingPartyId");

                    b.HasIndex("RequestingPartyId", "ReceivingPartyId")
                        .IsUnique();

                    b.ToTable("PoliticalAlliances", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalLeaderAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PoliticalLeaderAssignments", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PoliticalParties", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Admin@admin.com",
                            LastName = "Admin",
                            Name = "Admin",
                            Password = "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
                            Role = 1,
                            Status = true,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.AssignPosition", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Candidate", "Candidate")
                        .WithMany("AssignPositions")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.ElectivePosition", "ElectivePosition")
                        .WithMany("AssignPositions")
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany("AssignPositions")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("ElectivePosition");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.ElectivePosition", "ElectivePosition")
                        .WithMany()
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eVote360.Core.Domain.Entities.PoliticalParty", "PoliticalParty")
                        .WithMany()
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ElectivePosition");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalAlliance", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.PoliticalParty", "ReceivingParty")
                        .WithMany("AlliancesReceived")
                        .HasForeignKey("ReceivingPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.PoliticalParty", "RequestingParty")
                        .WithMany("AlliancesSent")
                        .HasForeignKey("RequestingPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceivingParty");

                    b.Navigation("RequestingParty");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalLeaderAssignment", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.PoliticalParty", "PoliticalParty")
                        .WithOne("PoliticalLeaderAssignment")
                        .HasForeignKey("eVote360.Core.Domain.Entities.PoliticalLeaderAssignment", "PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.User", "User")
                        .WithOne("PoliticalLeaderAssignment")
                        .HasForeignKey("eVote360.Core.Domain.Entities.PoliticalLeaderAssignment", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoliticalParty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("AssignPositions");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.ElectivePosition", b =>
                {
                    b.Navigation("AssignPositions");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalParty", b =>
                {
                    b.Navigation("AlliancesReceived");

                    b.Navigation("AlliancesSent");

                    b.Navigation("AssignPositions");

                    b.Navigation("PoliticalLeaderAssignment");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("PoliticalLeaderAssignment");
                });
#pragma warning restore 612, 618
        }
    }
}
